enum 50106 "JCA Application Action"
{
    value(0; "Event Invitation Mail")
    {
        Caption = 'Event Invitation Mail';
    }
    value(1; "Event Registration Confirmation Mail")
    {
        Caption = 'Event Registration Confirmation';
    }
    value(2; "Event Unregistration Confirmation Mail")
    {
        Caption = 'Event Unregistration Confirmation';
    }
    value(3; "Event Reminder Mail")
    {
        Caption = 'Event Reminder Mail';
    }
}